### ISSUE TITLE
The toolbar component is delay to display and slow than item selection (back-ground color)

### ISSUE THREAD

**Issue by MM-RYO** [lidorsystems/integralui-treeview#3]
Hi,

When I select an item by pressing Up/Down key. "contentVisibility" is delay displayed than the item selection

https://stackblitz.com/edit/integralui-treeview-keyboard-mxq2uz

![image](https://user-images.githubusercontent.com/1568013/105458071-d7de1a00-5cc2-11eb-8572-e28be6f4f79c.png)

**Comment by Lidor-Systems** [comment]
Apparently the position of custom content when item is selected using keyboard is not updated. We have checked this issue in code and now is fixed.

An updated version is already sent to your company representative.


Your example also updates the tree view layout whenever selection changes, within a handler to the selectionChanged event. The new update works without the need to update the tree view layout,but because layout is updated whenever a new item is selected (caused by your event handler), it seems that there is a flashing of item color. This is from CSS settings of Office theme, which you can override on your side.

**Comment by MM-RYO** [comment]
![image](https://user-images.githubusercontent.com/1568013/105952171-2c5f0c00-60ac-11eb-9d96-159f1bfbbbec.png)
I have upgraded to the latest version. but the issues are still there.
I selected a row then press the 'Up' / 'Down' key. the selected item being changed but the toolbar was still displayed on the previous selected item.

**Comment by Lidor-Systems** [comment]
We have checked this on an empty project using the code from the sample mentioned above. Its working, we have tried with single and multiple selection, in both cases whenever selection changes using keyboard, the toolbar position also updates and shows on selected item.

In internal TreeView code, we have set the toolbar position to update whenever item is selected, so it should work. Is there something in your code that may prevent this. Can you give us more details?

**Comment by MM-RYO** [comment]
> 
> 
> We have checked this on an empty project using the code from the sample mentioned above. Its working, we have tried with single and multiple selection, in both cases whenever selection changes using keyboard, the toolbar position also updates and shows on selected item.
> 
> In internal TreeView code, we have set the toolbar position to update whenever item is selected, so it should work. Is there something in your code that may prevent this. Can you give us more details?

Is there any API that could affect this if it's called?
I think we didn't do many things. below are the steps:
1. Base on the selected items to change content visibility
this.contentVisibility = selectedNodes.length > 1 ? IntegralUIContentVisibility.Hover : IntegralUIContentVisibility.Both;
2. Call updateLayout API of treeview 
if we didn't call it. the toolbar was still displayed on the old selected item

That's it.

**Comment by Lidor-Systems** [comment]
The new update we have sent you (integralui.base.list.js version 20.3.125) internally calls the updateSelectContentPos method whenever the item is selected. That is internally at the end of the processSelection method.

This method is currently set as protected, we can change it to be public and you can call it manually in your code whenever you need to update the position of the selected content template. But, this shouldn't be handled on your side, that's the reason it is made as protected.

Do you have this version 20.3.125 on your side? 
To check out, go to integralui/components/ and open the integralui.base.list.js file with some text editor.

**Comment by MM-RYO** [comment]
> 
> 
> The new update we have sent you (integralui.base.list.js version 20.3.125) internally calls the updateSelectContentPos method whenever the item is selected. That is internally at the end of the processSelection method.
> 
> This method is currently set as protected, we can change it to be public and you can call it manually in your code whenever you need to update the position of the selected content template. But, this shouldn't be handled on your side, that's the reason it is made as protected.
> 
> Do you have this version 20.3.125 on your side?
> To check out, go to integralui/components/ and open the integralui.base.list.js file with some text editor.

This version we haven't received it yet. I will check it with our sales. we have the version iui-web-treeview-203111-aYb4.zip.
and I just tested and found, even if the contentVisibility = IntegralUIContentVisibility.Both. the hover menu is still not displayed.

**Comment by Lidor-Systems** [comment]
This version is the newest one, sent on 25 Jan 2021.

In meantime you can quickly solve this by opening your current version of integralui.base.list.js and do the following:

1. Open the file with a text editor
2. Locate the string (it is the only one): 

```
this.selectionChanged.emit({item:null})}}}}
```

3. Replace it with this one: 

```
this.selectionChanged.emit({item:null})}this.updateSelectContentPos()}}}
```

The only difference is the call to updateSelectContentPos method.

**Comment by Lidor-Systems** [comment]
> I just tested and found, even if the contentVisibility = IntegralUIContentVisibility.Both. the hover menu is still not displayed.

Check out whether you have a hover template set in your component html. It should work.

**Comment by MM-RYO** [comment]
> Check out whether you have a hover template set in your component html. It should work.

there are no both hover and selected template by 'keyboard selection' when you select an item and press 1 time up or down and then move back. 
if I selected it with the mouse, it works fine. 

I just checked with our team. they said they haven't received the updated packages - 20.3.125
can you help to check it if not please send it again?

**Comment by robinNode** [comment]
> > Check out whether you have a hover template set in your component html. It should work.
> 
> there are no both hover and selected template by 'keyboard selection' when you select an item and press 1 time up or down and then move back.
> if I selected it with the mouse, it works fine.

**Comment by Lidor-Systems** [comment]
Hover content is only visible via mouse hovering, it is not available with keyboard.Using keyboard only the select content will appear.

**Note**   The update version 20.3.125 is now sent.

**Comment by MM-RYO** [comment]
> 
> 
> Hover content is only visible via mouse hovering, it is not available with keyboard.Using keyboard only the select content will appear.
> 
> **Note** The update version 20.3.125 is now sent.

but the mouse pointer is over on it and toolbar should be displayed. nvm this is a minor issue we can check it later.
